import type { Metadata } from "next";
import { Bona_Nova_SC } from "next/font/google";
import "./globals.css";

/*
const geistMono = Bona_Nova_SC({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap"
});
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
